#+TITLE: BIOS Vs UEFI
#+author: Rodrigo Francisco
#+date: <2021-09-09 Thu>
#+STARTUP: shrink

* Diferencias entre BIOS y UEFI

|Bios                                             | UEFI                                                                        |
-------------------------------------------------+-----------------------------------------------------------------------------|
Basic Input Output System                        | Unified Extensible Firmware Interface                                       |
-------------------------------------------------+-----------------------------------------------------------------------------|
Puede cargarse de dispositivos de 2TB o menos    | Puede cargarse de dispositivos de 2.2 TB o más grandes,                     |
                                                 | alcanzando un límite teórico de 9.4 zettabytes,                             |
                                                 | alcanzando un límite teórico de 9.4 zettabytes,                             |
                                                 | que es 3 veces más la información que se encuentra actualmente en Internet  |
-------------------------------------------------+-----------------------------------------------------------------------------|
Corren en modo de 16 bits y solo tiene un 1 MB   | Corre en modo de 32 o 64 bits.                                              |
de espacio para ejecturse                        |                                                                             |
-------------------------------------------------+-----------------------------------------------------------------------------|
No puede inicializar múltiples dispositivos de   | UEFI puede correr en modo de 32 o 64 bits, por lo que tiene más espacios    |
hardware a la vez, por lo tanto es lento.        | direccionables, lo que significa que el proceso de iniciado es más rápido.  |
-------------------------------------------------+-----------------------------------------------------------------------------|
Interfaz de configuración sencilla               | Como UEFI puede correr en 32 o 64 bits, se puede proveer una mejor interfaz |
                                                 | de usuario y que incluso permite el uso del *cursosr*                       |
-------------------------------------------------+-----------------------------------------------------------------------------|
No cuenta con mecanismos tanto sofisticados      | UEFI provee _Secure BOOT_, lo que permite que solo driver y servicos        |
de seguriddad                                    | autentificados se carguen en el proceso de arranque.                        |
-------------------------------------------------+-----------------------------------------------------------------------------|
Requiere de un *Boot loader*                     | No requiere de un bootloader                                                |
-------------------------------------------------+-----------------------------------------------------------------------------|
Busca el MBR en el primer sector del dispositivo | No busca en el primer sector del dipositivo, mantiene una lista de vólumnes |
de arranque seleccionado                         | de arranque válidos, en el llamado EFI Service Partition.                   |


+------------------------------+------------------------------+
| Hola estoy creando una tabla |Haciendo una segunda prueba de|
|con mucho contenido en emacs  |como de grande se puede hacer |
|                              |la tabla                      |
+------------------------------+------------------------------+
|Última prueba del tamañan de  |Debemos ber como se exporta a |
|una tabla.                    |github                        |
+------------------------------+------------------------------+


** Referencias
- Geek for Geeks. /UEFI(Unified Extensible Firmware Interface) and how it is different from BIOS/.
  Recuperado el 09 de septiembre de 2021
  En https://geeksforgeeks.org/uefiunified-extensible-firware-interface-and-how-is-different-from-bios/
